name: terraform CI CD pipeline
run-name: ${{ github.actor }} has triggered the pipeline.}

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: Build Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Install Terraform
        id: init
        run: terraform init
      - name: validate
        id: validate
        run: terraform validate
      - name: Plan
        id: plan
        run: terraform plan
      - name: Apply
        run: terraform apply --auto-approve